import {
  ArrowUpRight,
  Award,
  Bell,
  BookOpen,
  Bookmark,
  Building2,
  Calendar,
  Clock,
  ExternalLink,
  FileText,
  Film,
  Flag,
  Flame,
  Globe,
  Hash,
  Heart,
  Image,
  Layers,
  Link2,
  List,
  Mail,
  MapPin,
  MessageSquare,
  Moon,
  Music,
  Palette,
  PenLine,
  Skull,
  Sparkle,
  Star,
  Sun,
  Tag,
  Trophy,
  User,
  Users,
  Zap
} from 'lucide-react'

export const PROPERTY_ICON_OPTIONS = [
  { id: 'PenLine', Icon: PenLine },
  { id: 'List', Icon: List },
  { id: 'Star', Icon: Star },
  { id: 'Heart', Icon: Heart },
  { id: 'Skull', Icon: Skull },
  { id: 'Clock', Icon: Clock },
  { id: 'Calendar', Icon: Calendar },
  { id: 'Tag', Icon: Tag },
  { id: 'Hash', Icon: Hash },
  { id: 'Link2', Icon: Link2 },
  { id: 'ExternalLink', Icon: ExternalLink },
  { id: 'BookOpen', Icon: BookOpen },
  { id: 'Building2', Icon: Building2 },
  { id: 'ArrowUpRight', Icon: ArrowUpRight },
  { id: 'Sparkle', Icon: Sparkle },
  { id: 'Bookmark', Icon: Bookmark },
  { id: 'MapPin', Icon: MapPin },
  { id: 'Globe', Icon: Globe },
  { id: 'User', Icon: User },
  { id: 'Users', Icon: Users },
  { id: 'Mail', Icon: Mail },
  { id: 'FileText', Icon: FileText },
  { id: 'MessageSquare', Icon: MessageSquare },
  { id: 'Image', Icon: Image },
  { id: 'Film', Icon: Film },
  { id: 'Music', Icon: Music },
  { id: 'Palette', Icon: Palette },
  { id: 'Layers', Icon: Layers },
  { id: 'Award', Icon: Award },
  { id: 'Trophy', Icon: Trophy },
  { id: 'Flag', Icon: Flag },
  { id: 'Bell', Icon: Bell },
  { id: 'Zap', Icon: Zap },
  { id: 'Flame', Icon: Flame },
  { id: 'Sun', Icon: Sun },
  { id: 'Moon', Icon: Moon }
]

export const PROPERTY_ICON_MAP = Object.fromEntries(
  PROPERTY_ICON_OPTIONS.map(({ id, Icon }) => [id, Icon])
)

export function getPropertyIcon(name) {
  return PROPERTY_ICON_MAP[name] || List
}
